apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ${NAMESPACE}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://${RDS_ENDPOINT}:5432/oficina_db"
  SPRING_DATASOURCE_USERNAME: "oficina_user"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_BR_COM_FIAP: "DEBUG"
  SPRING_PROFILES_ACTIVE: "json"
  NEW_RELIC_APP_NAME: "${NEW_RELIC_APP_NAME}"
  NEW_RELIC_LOG_LEVEL: "info"
