apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
  ADMIN_USUARIO: "${ADMIN_USUARIO}"
  ADMIN_SENHA: "${ADMIN_SENHA}"
  JWT_SECRET: "${JWT_SECRET}"